# -*- coding: utf-8 -*-
"""ДЗ1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_7BMI1GM6bxIr6SntYGy6rgXDSw6o5Ue

Округляет число до заданного количества знаков после запятой.
"""

a = float(input())
b = int(input())
print(round(a, b))

"""Программа, которая находит среднее арифметическое двух чисел и округляет его до целого числа.

"""

a = int(input())
b = int(input())
n = 2
summa = a + b
res = summa / n
print(round(res))
input("Нажмите Enter, чтобы закрыть консоль...")