# -*- coding: utf-8 -*-
"""ДЗ2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q7i7K7JA3NTYWXVT7KvpBPRYj38xjDJ7

Чётное/Нечётное
"""

a = int(input())
n = 2
if (a % n) > 0:
  print("Это число не является чётным")
else:
  print("Это число чётное")

"""Большее из двух чисел"""

a = int(input())
b = int(input())
if a > b:
  print(a)
else:
  print(b)

"""Клетка шахматного поля"""

x = int(input("Координата X: "))
y = int(input("Координата Y: "))
if (x + y) % 2 == 1:
  print("YES")
else:
  print("NO")